from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("operators/", views.operators_view, name="operators"),
    path("operators/<int:pk>/delete/", views.delete_operator_view, name="operator-delete"),
    path("operators/<int:pk>/test-webhook/", views.test_webhook_view, name="operator-test-webhook"),
    path("sync/", views.sync_view, name="sync"),
    path("poll/", views.poll_view, name="poll"),
    path("fleet/withdrawn/", views.withdrawn_view, name="withdrawn"),
    path("fleet/<int:pk>/restore/", views.restore_vehicle_view, name="vehicle-restore"),
    path("fleet/<int:pk>/state/", views.vehicle_state_view, name="vehicle-state"),
    path("fleet/<int:pk>/override/", views.vehicle_override_view, name="vehicle-override"),
    path("fleet/<int:pk>/watch/create/", views.watch_create_view, name="watch-create"),
    path("fleet/<int:pk>/watch/<int:watch_id>/delete/", views.watch_delete_view, name="watch-delete"),
    path("fleet/<int:pk>/", views.vehicle_view, name="vehicle"),
    path("fleet/<str:code>/", views.public_fleet_view, name="public-fleet"),
    path("rules/types/", views.type_rules_view, name="type-rules"),
    path("rules/types/save/", views.type_rules_save_view, name="type-rules-save"),
    path("rules/vehicle/save/", views.vehicle_rule_save_view, name="vehicle-rule-save"),
    path("alerts/", views.alerts_view, name="alerts"),
    path("alerts/delete/<int:alert_id>/", views.delete_alert, name="delete-alert"),
    path("stats/", views.stats_view, name="stats"),
    path("register/", views.register_view, name="register"),
    path("alerts/clear/", views.clear_alerts, name="clear-alerts"),
]
