# Generated by Django 5.2.12 on 2026-03-14 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('theme_color', models.CharField(default='#00539f', max_length=7)),
                ('accent_color', models.CharField(default='#f0ad4e', max_length=7)),
                ('discord_webhook_url', models.TextField(blank=True)),
                ('api_base_url', models.CharField(default='https://bustimes.org/api', max_length=255)),
                ('vehicles_path', models.CharField(default='/vehicles/', max_length=100)),
                ('services_path', models.CharField(default='/services/', max_length=100)),
                ('vehicle_journeys_path', models.CharField(default='/vehiclejourneys/', max_length=100)),
                ('operator_param_name', models.CharField(default='operator', max_length=50)),
                ('training_code', models.CharField(blank=True, max_length=50)),
                ('dead_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PollState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_banner_message', models.TextField(blank=True)),
                ('latest_banner_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('latest_banner_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocations.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(default='bus', max_length=50)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.operator')),
            ],
            options={
                'ordering': ['line_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bustimes_vehicle_id', models.BigIntegerField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('fleet_number', models.IntegerField(blank=True, null=True)),
                ('fleet_code', models.CharField(blank=True, max_length=50)),
                ('reg', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=200)),
                ('operator_name', models.CharField(blank=True, max_length=200)),
                ('garage_name', models.CharField(blank=True, max_length=200)),
                ('withdrawn', models.BooleanField(default=False)),
                ('hidden_because_withdrawn', models.BooleanField(default=False)),
                ('bustimes_name', models.CharField(blank=True, max_length=200)),
                ('bustimes_notes', models.TextField(blank=True)),
                ('livery_css', models.CharField(blank=True, max_length=100)),
                ('trainer', models.BooleanField(default=False)),
                ('manual_state', models.CharField(choices=[('ACTIVE', 'Active'), ('VOR', 'VOR')], default='ACTIVE', max_length=10)),
                ('return_alert_armed', models.BooleanField(default=False)),
                ('last_seen_journey_at', models.DateTimeField(blank=True, null=True)),
                ('current_route', models.CharField(blank=True, max_length=100)),
                ('current_destination', models.CharField(blank=True, max_length=200)),
                ('current_allocation_level', models.CharField(blank=True, max_length=20)),
                ('last_journey_id', models.BigIntegerField(blank=True, null=True)),
                ('last_alert_key', models.CharField(blank=True, max_length=255)),
                ('override_name', models.CharField(blank=True, max_length=200)),
                ('override_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.operator')),
            ],
            options={
                'ordering': ['fleet_number', 'fleet_code'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200)),
                ('fleet_code', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('route_name', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.operator')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocations.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('last_trigger_journey_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.operator')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.vehicle')),
            ],
            options={
                'ordering': ['vehicle__fleet_number', 'vehicle__fleet_code', 'route_name'],
            },
        ),
        migrations.CreateModel(
            name='TypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare')], max_length=20)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.operator')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.route')),
            ],
            options={
                'unique_together': {('operator', 'vehicle_type', 'route')},
            },
        ),
        migrations.CreateModel(
            name='VehicleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare')], max_length=20)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.operator')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.vehicle')),
            ],
            options={
                'unique_together': {('operator', 'vehicle', 'route')},
            },
        ),
    ]
