# Generated by Django 5.2.12 on 2026-03-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_alert_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
