# Generated by Django 5.2.12 on 2026-03-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('uses_remaining', models.IntegerField(default=1)),
            ],
        ),
    ]
