# Generated by Django 5.2.12 on 2026-03-14 23:56

import allocations.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0004_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitecode',
            name='infinite_uses',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=allocations.models.generate_invite_code, editable=False, max_length=10, unique=True),
        ),
    ]
