# Generated by Django 5.2.12 on 2026-03-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0005_invitecode_created_at_invitecode_infinite_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typerule',
            name='level',
            field=models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('RAIL_REPLACEMENT', 'Rail Replacement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclerule',
            name='level',
            field=models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('RAIL_REPLACEMENT', 'Rail Replacement')], max_length=20),
        ),
    ]
