# Generated by Django 5.2.12 on 2026-03-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0006_alter_typerule_level_alter_vehiclerule_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='rail_replacement_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
