# Generated by Django 5.2.12 on 2026-03-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0007_operator_rail_replacement_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorCustomCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.operator')),
            ],
            options={
                'unique_together': {('operator', 'code')},
            },
        ),
    ]
