# Generated by Django 5.2.12 on 2026-03-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0009_operatorfollow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['operator'], name='allocations_operato_6ea4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['bustimes_vehicle_id'], name='allocations_bustime_5c26ce_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['current_route'], name='allocations_current_545289_idx'),
        ),
    ]
