# Generated by Django 5.2.12 on 2026-03-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0010_vehicle_allocations_operato_6ea4a0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='discord_webhook_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
