# Generated by Django 5.2.12 on 2026-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0013_supervisorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorrequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
