# Generated by Django 5.2.12 on 2026-03-17 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0015_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('guild_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.operator')),
            ],
        ),
    ]
