# Generated by Django 5.2.12 on 2026-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0016_discordsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordsubscription',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='discordsubscription',
            name='channel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
